const ActionTypes = {
  ADD_TODO: "ADD_TODO",
  CLEAR_TODOS: "CLEAR_TODOS",
  SET_FILTER: "SET_FILTER",
  TOGGLE_TODO: "TOGGLE_TODO",
  FILTER_ALL: "FILTER_ALL",
  FILTER_COMPLETED: "FILTER_COMPLETED",
  FILTER_ACTIVE: "FILTER_ACTIVE"
};

export default ActionTypes;